version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres-con
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "masterkey"
    volumes:
          - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      postgres:
        aliases:
          - postgres
  weather:
    container_name: weather
    image: weather
    ports:
      - "3541:3541"
    restart: unless-stopped
    networks:
      postgres:
        aliases:
          - service
networks:
  postgres:
    driver: bridge