version: "3.9"
services:
  postgres:
    container_name: postgres-con
    image: postgres-con
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      postgres:
        aliases:
          - postgresdb
  weather:
    container_name: weather
    image: weather
    stdin_open: true
    ports:
      - "3541:3541"
    restart: unless-stopped
    networks:
      postgres:
        aliases:
          - weather
networks:
  postgres:
    driver: bridge