#to connect db
#for localhost
#dsn = "postgres://postgres:masterkey@localhost:5432/weather?sslmode=disable"
#for Docker
dsn = "postgres://postgres:masterkey@postgresdb:5432/weather?sslmode=disable"
#http server parameters
httpsrv = ":3541"
#external API key
appid = "effe2454b05e87a8f799b78681cbd4e1"
#interval to get weather by API
interval = 60

#logger parameters
[logger]
level = "INFO"
logfile = "./log.txt"